site_name: Laplacians.jl

site_description: Graph analysis inspired by graph Laplacians and the needs of researchers at YINS

theme: mkdocs

repo_url: https://github.com/danspielman/Laplacians.jl

pages:
- About: 'about.md'
- User Guide:
    - Installation: 'Installation.md'
    - Using Julia: 'Julia.md'
    - Examples: 'Examples.md'
    - Low Stretch Spanning Trees: 'LSST.md'
    - Sparse matrices as graphs: 'CSCgraph.md'
    - Solvers: 'solvers.md'
- Developing:
    - Devleoping Laplacians: 'Developing.md'
- API:
    - Whole API: 'wholeAPI.md'
    - graphGenerators: 'graphGeneratorsAPI.md'
    - IO: 'IOAPI.md'

docs_dir: 'docs'

site_favicon: lambda2.ico


markdown_extensions:
  - extra
  - tables
  - fenced_code

extra_css:
  - Laplacians.css

extra_javascript:
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML
  - mathjaxhelper.js


use_directory_urls: false
