site_name: Laplacians.jl
repo_url: https://github.com/danspielman/Laplacians.jl
site_description: Spectral and Algebraic graph algorithms, emphasizing the graph Laplacian.

theme: readthedocs


pages:
- About: 'index.md'
- User Guide:
    - Installation: 'Installation.md'
    - Using Julia: 'Julia.md'
    - Examples: 'Examples.md'
    - Sparse matrices as graphs: 'CSCgraph.md'
    - Solving Linear Equations: 'usingSolvers.md'
    - Low Stretch Spanning Trees: 'LSST.md'
- Developing:
    - Developing Laplacians: 'Developing.md'
- API:
    - generators: 'graphGenerators.md'
    - operators: 'operators.md'
    - graphUtils: 'graphUtils.md'
    - graphAlgs : 'graphAlgs.md'
    - IO: 'IO.md'
    - solvers: 'solvers.md'
    - sparsification: 'sparsification.md'
    - akpw: 'akpw.md'
    - treeAlgs: 'treeAlgs.md'
    - randTrees: 'randTrees.md'
    - localClustering: 'localClustering.md'
    - Private Functions: 'privateFuncs.md'
    - All of the above: 'indexOfAll.md'

docs_dir: 'build'

site_favicon: lambda2.ico

extra_css:
  - assets/Laplacians.css

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML
  - assets/mathjaxhelper.js

markdown_extensions:
  - extra
  - tables
  - fenced_code

use_directory_urls: false




